// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 ", "[example]")
{
	char people[M][N][L];
	int length;
	int num;
	length = makeDB(people);
	cout << people[2][3] << endl;
	REQUIRE(length == 100);
	REQUIRE(strcmp(people[2][3], "Travis") == 0);
	printRecord(people, length);
	cout << "--------------------------------------------------\n";
	printEmail(people, length);
}

TEST_CASE("Ex2 ", "[example]")
{
	char people[M][N][L];
	int length;
	int num;
	length = makeDB(people);

	num = getNumMale(people, length);
	REQUIRE(num == 47);
	cout << "--------------------------------------------------\n";
}
